apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
type: Opaque
stringData:
  AUTH_SECRET: '' # -- openssl rand -base64 32
  ENCRYPTION_KEY: '' # -- openssl rand -hex 16
  # -- Recommend using Cloud-based Platform as a Service (PaaS) solutions for PostgreSQL and Redis to ensure high availability.
  REDIS_URL: ''
  DB_CONNECTION_URI: ''
