# Enable the Portainer Enterprise Edition
enterpriseEdition:
  enabled: true

service:
  # Set the httpNodePort and edgeNodePort only if the type is NodePort
  # For Ingress, set the type to be ClusterIP and set ingress.enabled to true
  # For Cloud Providers, set the type to be LoadBalancer
  type: NodePort

tls:
  # If set, Portainer will be configured to use TLS only
  force: true
