version: '3'
volumes:
  nginxproxymanager_data:
  nginxproxymanager_ssl:
  nginxproxymanager_db:
services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - 80:80
      - 81:81
      - 443:443
    environment:
      - DB_MYSQL_HOST=nginxproxymanager-db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npm
      - DB_MYSQL_PASSWORD=npm
      - DB_MYSQL_NAME=npm
    volumes:
      - nginxproxymanager_data:/data
      - nginxproxymanager_ssl:/etc/letsencrypt
    restart: unless-stopped
    depends_on:
      - nginxproxymanager-db
    healthcheck:
      test: ['CMD', '/bin/check-health']
      interval: 10s
      timeout: 5s

  nginxproxymanager-db:
    image: jc21/mariadb-aria:latest
    container_name: nginx-proxy-manager-db
    environment:
      - MYSQL_ROOT_PASSWORD=npm
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm
      - MYSQL_PASSWORD=npm
    volumes:
      - nginxproxymanager_db:/var/lib/mysql
    restart: unless-stopped
