version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.37.9
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config:/etc/prometheus
      - ./prometheus_data:/prometheus
    command: '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

volumes:
  prometheus_data:
    driver: local
