version: '3'
services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    ports:
      - 9000:9000
      - 9443:9443
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  portainer_data:
    driver: local
