version: '3'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/traefik.yml
    env_file:
      - ./config/traefik.env

  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.localhost`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.middlewares=whoa
      - traefik.http.middlewares.whoa.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.whoa.headers.customrequestheaders.X-Forwarded-Port=443
      - traefik.http.middlewares.whoa.headers.customrequestheaders.X-Forwarded-Host=whoami.localhost
      - traefik.http.middlewares.whoa.headers.customrequestheaders.X-Forwarded-Uri=https://whoami.localhost
      - traefik.http.middlewares.whoa.headers.customrequestheaders.X-Forwarded-Method=GET
