global:
  scrape_interval: '1m'
  scrape_timeout: '15s'
  evaluation_interval: '1m'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  ## Example
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  ## Example
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
