apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: your-certificate
  namespace: cert-manager
spec:
  secretName: your-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - your.domain.com
