version: '3'
services:
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
